package com.lgb.webnetflix.mapper;

import com.lgb.webnetflix.model.User;
import com.lgb.webnetflix.model.UserExample;
import com.lgb.webnetflix.model.UserKey;
import com.lgb.webnetflix.model.UserWithBLOBs;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;
@Mapper
public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Apr 04 20:33:31 ICT 2023
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Apr 04 20:33:31 ICT 2023
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Apr 04 20:33:31 ICT 2023
	 */
	int insert(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Apr 04 20:33:31 ICT 2023
	 */
	int insertSelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Apr 04 20:33:31 ICT 2023
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Apr 04 20:33:31 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Apr 04 20:33:31 ICT 2023
	 */
	int updateByExample(@Param("row") User row, @Param("example") UserExample example);
	
	
	
	
	//custom query
	List<Map<String,Object>> getAllUser(Map<String,Object> para );
}